### ISSUE TITLE
Sudden slow down in performance

### ISSUE THREAD

**Issue by darioringach** [DeepLabCut/DeepLabCut-live-GUI#10]
I am experiencing a sudden slow-down in performance in DLC Live, and I was wondering if anyone has seen this before and knows how to fix it.

I am running a simple python script that receives imagery data over memory mapped files:

![Capture](https://user-images.githubusercontent.com/6867537/112509814-10938180-8d4e-11eb-896b-15a8d22656fa.PNG)

The pose estimation takes normally about 12-14msec... but the, all of sudden, it jumps to ~140ms:

![Capture2](https://user-images.githubusercontent.com/6867537/112510202-72ec8200-8d4e-11eb-86b7-afaa9c9f9900.PNG)

Any ideas what this could be?  It happens after this processing loops has been working for 2-3 minutes.   It always starts Ok and then it slows down.  This is running on a Quadro M6000 24GB.

Thank you!
--
Dario

**Comment by darioringach** [comment]
...and if you keep running, it will jump again and slow even more:

![Capture3](https://user-images.githubusercontent.com/6867537/112512293-7a148f80-8d50-11eb-8c01-45a01018321d.PNG)

**Comment by MMathisLab** [comment]
Hi @darioringach i can confirm I’ve never had this in our dlc-live code or our dlc GUI, or bonsai or autopilot (to the extend we did a lot of testing for our paper).

**Comment by darioringach** [comment]
> Hi @darioringach i can confirm I’ve never had this in our dlc-live code or our dlc GUI, or bonsai or autopilot (to the extend we did a lot of testing for our paper).

Thanks. I guess I will first try with a different GPU card.

**Comment by MMathisLab** [comment]
I doubt it’s the gpu; can you run the dlc-live benchmarking code, that profiles the system.

**Comment by darioringach** [comment]
> I doubt it’s the gpu; can you run the dlc-live benchmarking code, that profiles the system.

How long does the benchmarking code runs for?  It's been looping for over 2 hours now doing Run #i out of 6.

**Comment by darioringach** [comment]
I can confirm that this was a specific problem with the Quadro M6000.  
Everything works fine on an RTX 2080 Ti.

**Comment by MMathisLab** [comment]
crazy! Thanks for testing this @darioringach - super valuable to know :)
