### ISSUE TITLE
Key Error when setting process

### ISSUE THREAD

**Issue by nithikc** [DeepLabCut/DeepLabCut-live-GUI#19]
Hi, I am getting a keyerror when I click on set process. Is this supposed to happen?

**Comment by AdityaPujari22** [comment]
Hi, I am having the same issue when setting my process. What's the solution?

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
With a fresh install, using the DLCLiveGUI, I try to set the Processor to MouseLickLED and observe: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/onecore/anaconda3/envs/dlc-live/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/onecore/anaconda3/envs/dlc-live/lib/python3.7/site-packages/dlclivegui/dlclivegui.py", line 1004, in set_proc
    self.cfg["processor_args"][self.dlc_proc_dir.get()][
KeyError: '/home/onecore/Documents/DeepLabCut-live-master/example_processors/MouseLickLED'

Side, probably not related, but confusing to me:
* TeensyLaser has: from dlclive.processor.processor import Processor
* MouseLickLED has: from dlclive import Processor
