### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by qiangzhengPKU** [DeepLabCut/DeepLabCut-live-GUI#2]
**Describe the bug:**
Running deeplabcut-live-gui on Windows 10 in a conda environment fails due to "OSError: [WinError 126] The specified module could not be found"(this words is just the same as "找不到指定模块" in my  screenshot), but i just used "dlclivegui" after installing.

![image](https://user-images.githubusercontent.com/70259026/91276122-aadd1800-e7b3-11ea-91e8-c0b76f01c31a.png)

 I will be very appreciated if you could give me an reply.

**Comment by qiangzhengPKU** [comment]
Now i assume the reason is  the lack of camera......

**Comment by gkane26** [comment]
Yep -- the tisgrabber_x64.dll file needs to be on the path somewhere. I just submitted a PR  (see #4) to catch this exception so the GUI will work if you don't want to install/use imaging source cameras.

To clarify, you are not trying to use Imaging Source cameras? If so, you'll need to install their drivers and C library (see the [camera support docs](https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/windows-camera/docs/camera_support.md), which are also updated in this PR).
