### ISSUE TITLE
How to generate a csv file

### ISSUE THREAD

**Issue by Shawn0629** [DeepLabCut/DeepLabCut-live-GUI#23]
I have used dlc before, and dlc can generate csv files about the coordinates and positions of animals. But it seems that there is no such function in dlclivegui, can you help me solve this problem. 
![螢幕擷取畫面 2023-05-23 115227](https://github.com/DeepLabCut/DeepLabCut-live-GUI/assets/90035520/add0d1c0-5671-4dc7-a8a1-52ad299cfd03)
Thank you so much!

**Comment by MMathisLab** [comment]
Hi @Shawn0629 we only support h5 export/saving. It's a fantastic file type which I strongly recommend over csv, and you can open it in Python, matlab, R, etc much more efficiently. Check out DLCUtils for example code. Also there are h5 readers and you can export to csv, if you want. 

This H5 forcing is a bit my way to really try to be educational about a better data standards the field, and now fields are rapidly adopting 🤗 (NWB uses h5).
