### ISSUE TITLE
The GUI is very small on Ubuntu 20.04

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut-live-GUI#3]
I might be the only person who is facing this issue but I didn't have it for majority of GUI based open-source softwares. I have also documented my question in AskUbuntu. I was wondering if you have tried this with Ubuntu 20.04?

![Screenshot from 2020-09-26 22-41-31](https://user-images.githubusercontent.com/1892917/94354707-bab67900-004b-11eb-8f6c-216b5b30e29d.png)

https://askubuntu.com/questions/1278043/how-can-i-make-the-size-of-a-gui-in-ubuntu-20-04-larger

**Comment by MMathisLab** [comment]
That is the correct size; the windows that hold the image pop up separately and are larger. Yes, we use Ubuntu 20
