### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by darioringach** [DeepLabCut/DeepLabCut-live-GUI#7]
All seemed to have installed fine, but when I run dlclivegui in the environment I get:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/6867537/111072447-e2818800-8497-11eb-84ec-494012ad2a21.png">

Is this just a missing imaging source driver?

**Comment by MMathisLab** [comment]
hi @darioringach, seems maybe the driver is missing? did you install the driver first (i.e., see here: https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/docs/camera_support.md)

**Comment by darioringach** [comment]
> hi @darioringach, seems maybe the driver is missing? did you install the driver first (i.e., see here: https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/docs/camera_support.md)

I tried, but it would not let me without a camera installed... but I wanted to use an OpenCV compatible camera instead.

**Comment by MMathisLab** [comment]
> I tried, but it would not let me without a camera installed... 

not sure I follow; if you plug camera in to comp, and install driver it tells you it cannot install drivers?

**Comment by darioringach** [comment]
The driver installation requires a The Imaging Source camera connected:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/6867537/111081589-3f456880-84c1-11eb-8729-1ac6dd0d48c4.png">

But I don't have one, so I can't proceed.  Instead a have other cameras that are compatible with OpenCV.  Perhaps dlclivegui insists in loading the driver even if one does not want to work with TIS cameras?

**Comment by gkane26** [comment]
hi @darioringach -- I believe we fixed this issue in #2, and it's possible that the version on pypi doesn't include this fix. Did you install from pypi? If so, can you try reinstalling directly from github?
```
pip uninstall deeplabcut-live-gui
pip install git+https://github.com/DeepLabCut/DeepLabCut-live-GUI
```

**Comment by darioringach** [comment]
Thanks Gene...  that worked!
--
Dario

**Comment by MMathisLab** [comment]
^ cool! @darioringach can you confirm if it worked from github or from pypi?

**Comment by darioringach** [comment]
> ^ cool! @darioringach can you confirm if it worked from github or from pypi?

Github

**Comment by MMathisLab** [comment]
@AlexEMG can you push the latest to pypi?

**Comment by MMathisLab** [comment]
on pypi now!
