### ISSUE TITLE
Problem loading model

### ISSUE THREAD

**Issue by darioringach** [DeepLabCut/DeepLabCut-live-GUI#9]
I decided to start slow...
Installed on dlc-live on Windows -- no problem.  Tensor flow versions match (1.15.4)
I initialize the camera...  it comes up Ok.  I have no Processor for now.  
I select the model and click "Init DLC" and I get the out of range error in the image below.
Did I do something wrong?  

![Capture](https://user-images.githubusercontent.com/6867537/111890947-8775f680-89ab-11eb-9bd9-303c4d362c33.PNG)

**Comment by MMathisLab** [comment]
Hi @darioringach make sure you select the whole model folder (not a particular file within it, should work then!)

**Comment by darioringach** [comment]
@MMathisLab is the whole model folder the one containing "dlc-models", "labeled-data"... and so on?  If so, I get:

```
  File "c:\users\dario\anaconda3\envs\dlc-live\lib\site-packages\dlclive\dlclive.py", line 164, in read_config
    f"The pose configuration file for the exported model at {cfg_path} was not found. Please check the path to the exported model directory"
FileNotFoundError: The pose configuration file for the exported model at C:\Users\dario\Documents\eye_ir-Dario-2021-03-16\pose_cfg.yaml was not found. Please check the path to the exported model directory
```
I get the same if I point to dlc-models instead.

**Comment by MMathisLab** [comment]
Hi Dario, no when you run dlc.export_model it creates a whole new zip file. This is what is then used in dlc live. Namely, export, move zip, un-zip, and point to this new folder.

**Comment by darioringach** [comment]
> Hi Dario, no when you run dlc.export_model it creates a whole new zip file. This is what is then used in dlc live. Namely, export, move zip, un-zip, and point to this new folder.

Ok... then I am missing something. Can't find how to export the model in the GUI nor the in the steps described in the docs. How do I export the model?  Thanks again!

**Comment by MMathisLab** [comment]
Note on where to point to:

https://github.com/DeepLabCut/DeepLabCut-live-GUI#configure-deeplabcut-network

Note, of course this GUI assumes you have dlc-live, which points you on how to export your DeepLabCut model:

![Screen Shot 2021-03-21 at 7 05 10 PM](https://user-images.githubusercontent.com/28102185/111915821-63341b80-8a78-11eb-868c-701f1aad3a5e.png)


In short, please within DeepLabCut run `deeplabcut.export_model`:

https://github.com/DeepLabCut/DeepLabCut/blob/a9fdb5f401893dc2dc4c16a8818371215cda1ac0/docs/HelperFunctions.md#new-model-export-function

**Comment by darioringach** [comment]
Got it...  seems to load now (maybe just add one Tab to the GUI for exporting?). 

I do get a warning:

`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2` 

Just ignore?

**Comment by AlexEMG** [comment]
Yes, that's just regarding your TF installation... more info on what Advanced Vector Extensions2 is about: https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

Quoting from there ... "If you don't have a GPU and want to utilize CPU as much as possible, you should build tensorflow from the source optimized for your CPU with AVX, AVX2, and FMA enabled if your CPU supports them."
